### ISSUE TITLE
Error in the journactl of rocketchat

### ISSUE THREAD

**Issue by yodatak** [RocketChat/rocketchat_nextcloud#19]
mars 30 18:55:50 X RocketChat[1614954]: {"level":50,"time":"2022-03-30T16:55:50.799Z","pid":1614954,"hostname":"CX","name":"System","msg":"Exception while invoking method logoutCleanUp 'Match error: Expected object, got null'"}

I don't know if its important but i got this error when i connect to the app

**Comment by yodatak** [comment]
mars 30 18:57:38 X RocketChat[1614954]: Exception in onLogout callback TypeError: Cannot read property '_id' of undefined
mars 30 18:57:38 X RocketChat[1614954]:     at server/hooks/sauMonitorHooks.ts:22:21
mars 30 18:57:38 X RocketChat[1614954]:     at packages/callback-hook/hook.js:141:18
mars 30 18:57:38 X RocketChat[1614954]:     at packages/accounts-base/accounts_server.js:266:7
mars 30 18:57:38 X RocketChat[1614954]:     at Hook.forEach (packages/callback-hook/hook.js:110:15)
mars 30 18:57:38 X RocketChat[1614954]:     at Hook.each (packages/callback-hook/hook.js:122:17)
mars 30 18:57:38 X RocketChat[1614954]:     at AccountsServer._successfulLogout (packages/accounts-base/accounts_server.js:264:24)
mars 30 18:57:38 X RocketChat[1614954]:     at MethodInvocation.methods.logout (packages/accounts-base/accounts_server.js:663:16)
mars 30 18:57:38 X RocketChat[1614954]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
mars 30 18:57:38 X RocketChat[1614954]:     at packages/ddp-server/livedata_server.js:769:19
mars 30 18:57:38 X RocketChat[1614954]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
mars 30 18:57:38 X RocketChat[1614954]:     at packages/ddp-server/livedata_server.js:767:46
mars 30 18:57:38 X RocketChat[1614954]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
mars 30 18:57:38 X RocketChat[1614954]:     at packages/ddp-server/livedata_server.js:765:46
mars 30 18:57:38 X RocketChat[1614954]:     at new Promise (<anonymous>)
mars 30 18:57:38 X RocketChat[1614954]:     at Session.method (packages/ddp-server/livedata_server.js:739:23)
mars 30 18:57:38 X RocketChat[1614954]:     at packages/ddp-server/livedata_server.js:603:43
mars 30 18:57:38 X RocketChat[1614954]: {"level":50,"time":"2022-03-30T16:57:38.535Z","pid":1614954,"hostname":"X","name":"System","msg":"Exception while invoking method logoutCleanUp 'Match error: Expected object, got null'"}

**Comment by pierrelocus** [comment]
Thanks for the info, I'll investigate on that, perhaps because I always logout before login for now (will be refactored soon to log out of Rocket only when logging out of NextCloud, but it's to avoid someone to get someone else's rocket chat account open because of token). Will keep you updated :)

**Comment by yodatak** [comment]
Hey i just git clone the latest version same and no error in journactl other that this : 
mars 31 00:51:47 XXX RocketChat[1614954]: {"level":50,"time":"2022-03-30T22:51:47.843Z","pid":1614954,"hostname":"XX","name":"System","msg":"Exception while invoking method logoutCleanUp 'Match error: Expected object, got null'"}
