### ISSUE TITLE
Rocket Chat logs out when reloading with existing user

### ISSUE THREAD

**Issue by AngelMatilla** [RocketChat/rocketchat_nextcloud#23]
I have connected an existing instance of Rocket Chat (4.5.4) with an existing instance of Nextcloud (Nextcloud Hub II (23.0.3)). 
In both platforms, the user associated to my email address exist and I have even changed the password so that it matches in both servers. I have installed and configured the Rocket Chat app in Nextcloud as in the youtube video in the documentation. When clicking on the Rocket Chat tab on Nextcloud I am requested to enter a username and password. 

I imagine it does not necessarily associate existing users with matching email address. However after login in, if I refresh the page or switch between Nextcloud tabs it logs out with the following error message: 

```
  __action__ is not allowed
```

and this is the error log from the inspector console on Chromium: 

```
Blocked autofocusing on a <input> element in a cross-origin subframe.

...

0f6307921c60cb01b70885b26651947c8262f4da.js?meteor_js_resource=true:1496 Uncaught (in promise) r {isClientSafe: true, error: 'error-action-not-allowed', reason: 'Login neccessary', details: {…}, message: 'Login neccessary [error-action-not-allowed]', …}

...

r {isClientSafe: true, error: 'error-invalid-user', reason: 'Invalid user', details: {…}, message: 'Invalid user [error-invalid-user]', …}
```

**Comment by brendan-pike** [comment]
I may be effected by this bug also.  I setup a fresh docker installation for RC and connected it to an existing nextcloud (23.0.3) installation.  At first it all worked, users were auto-created but after a short while my NC admin user will no longer auto login. When I visit the RC link I see this in NC logs:

`{"reqId":"KEzRMZNfyi0K9pbTOwWa","level":3,"time":"2022-04-07T07:36:22+00:00","remoteAddr":"xxxx:xxxx:xxxx:x:xxxx:xxxx:xxxx:xxxx","user":"admin","app":"PHP","method":"GET","url":"/apps/rocketchat_nextcloud/","message":"Undefined array key \"authToken\" at /var/www/nextcloud/apps/rocketchat_nextcloud/lib/Rocket/User.php#217","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.27","version":"23.0.3.2","exception":{"Exception":"Error","Message":"Undefined array key \"authToken\" at /var/www/nextcloud/apps/rocketchat_nextcloud/lib/Rocket/User.php#217","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/rocketchat_nextcloud/lib/Rocket/User.php","line":217,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/rocketchat_nextcloud/lib/Controller/PageController.php","line":63,"function":"findByNcUserId","class":"OCA\\RocketchatNextcloud\\Rocket\\User","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\RocketchatNextcloud\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}`

However a for a lesser priviledged test user it works fine.

**Comment by seraphyn** [comment]
I can sign that.
A login works, but once another app etc. is selected in Nextcloud you are logged out again.
This makes the integration useless, there should then be taken an app, or an extra browser tab.

**Comment by ruvenss** [comment]
@AngelMatilla can we have the Rocket.Chat logs as well please?

**Comment by GEN-Europe** [comment]
```
I20220421-17:59:42.425(2) Exception in onLogout callback TypeError: Cannot read property '_id' of undefined     at server/hooks/sauMonitorHooks.ts:22:21     at packages/callback-hook/hook.js:141:18     at packages/accounts-base/accounts_server.js:266:7     at Hook.forEach (packages/callback-hook/hook.js:110:15)     at Hook.each (packages/callback-hook/hook.js:122:17)     at AccountsServer._successfulLogout (packages/accounts-base/accounts_server.js:264:24)     at MethodInvocation.methods.logout (packages/accounts-base/accounts_server.js:663:16)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)     at packages/ddp-server/livedata_server.js:769:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/ddp-server/livedata_server.js:767:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/ddp-server/livedata_server.js:765:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:739:23)     at packages/ddp-server/livedata_server.js:603:43 
{"level":50,"time":"2022-04-21T15:59:42.525Z","pid":117497,"hostname":"rocketchat-ubuntu-2gb-nbg1-1","name":"System","msg":"Exception while invoking method logoutCleanUp 'Match error: Expected object, got null'"} 
{"level":50,"time":"2022-04-21T16:00:59.082Z","pid":117497,"hostname":"rocketchat-ubuntu-2gb-nbg1-1","name":"System","msg":"Exception while invoking method autoTranslate.getProviderUiMetadata 'Login neccessary [error-action-not-allowed]'"} 
{"level":50,"time":"2022-04-21T16:00:59.086Z","pid":117497,"hostname":"rocketchat-ubuntu-2gb-nbg1-1","name":"System","msg":"Exception while invoking method cloud:checkRegisterStatus 'Invalid user [error-invalid-user]'"} 
{"level":50,"time":"2022-04-21T16:00:59.089Z","pid":117497,"hostname":"rocketchat-ubuntu-2gb-nbg1-1","name":"System","msg":"Exception while invoking method autoTranslate.getSupportedLanguages 'Auto-Translate is not allowed [error-action-not-allowed]'"} 
{"level":50,"time":"2022-04-21T16:00:59.091Z","pid":117497,"hostname":"rocketchat-ubuntu-2gb-nbg1-1","name":"System","msg":"Exception while invoking method logoutCleanUp 'Match error: Expected object, got null'"} 
```

**Comment by AngelMatilla** [comment]
> @AngelMatilla can we have the Rocket.Chat logs as well please?

@ruvenss See the answer from @GEN-Europe above

**Comment by deadmanIsARabbit** [comment]
I can confirm this.
Our users are provided from a LDAP. 

Maybe this provides you with further informations:

```
May  3 10:19:28 cs-be-s060 rocketchat[521039]: null {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: null
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: null {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: listCustomSounds {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: apps/is-enabled {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: listCustomUserStatus {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: loadLocale {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: getUserRoles {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: e2e.fetchMyKeys {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: loadLocale {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: '8hHt9FMi3af5WhEwL'
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:28 cs-be-s060 rocketchat[521039]: null {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:28 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:28 cs-be-s060 rocketchat[521039]:  userId: null
May  3 10:19:28 cs-be-s060 rocketchat[521039]: }
May  3 10:19:29 cs-be-s060 rocketchat[521039]: autoTranslate.getProviderUiMetadata {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  userId: null
May  3 10:19:29 cs-be-s060 rocketchat[521039]: }
May  3 10:19:29 cs-be-s060 rocketchat[521039]: autoTranslate.getSupportedLanguages {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  userId: null
May  3 10:19:29 cs-be-s060 rocketchat[521039]: }
May  3 10:19:29 cs-be-s060 rocketchat[521039]: loadHistory {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  userId: null
May  3 10:19:29 cs-be-s060 rocketchat[521039]: }
May  3 10:19:29 cs-be-s060 rocketchat[521039]: logoutCleanUp {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  id: 'hhRSjhaSPzBz8975G',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  clientAddress: null,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  httpHeaders: {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'x-real-ip': 'XXX.XXX.XXX.XX',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    host: 'rocketchat.my.domain',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    'accept-language': 'de-DE,de;q=0.9,en-DE;q=0.8,en-GB;q=0.7,en;q=0.6,en-US;q=0.5'
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  },
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  userId: null
May  3 10:19:29 cs-be-s060 rocketchat[521039]: }
May  3 10:19:29 cs-be-s060 rocketchat[521039]: Exception while invoking method 'logoutCleanUp' Error: Match error: Expected object, got null
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at check (packages/check/match.js:36:17)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at MethodInvocation.logoutCleanUp (server/methods/logoutCleanUp.js:8:3)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:769:19
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:767:46
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:765:46
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at new Promise (<anonymous>)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at Session.method (packages/ddp-server/livedata_server.js:739:23)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:603:43
May  3 10:19:29 cs-be-s060 rocketchat[521039]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at errorClass.<anonymous> (packages/check/match.js:91:27)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at new errorClass (packages/meteor.js:660:17)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at check (packages/check/match.js:36:17)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at MethodInvocation.logoutCleanUp (server/methods/logoutCleanUp.js:8:3)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:769:19
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:767:46
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:765:46
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at new Promise (<anonymous>)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at Session.method (packages/ddp-server/livedata_server.js:739:23)
May  3 10:19:29 cs-be-s060 rocketchat[521039]:    at packages/ddp-server/livedata_server.js:603:43 {
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  isClientSafe: true,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  error: 400,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  reason: 'Match failed',
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  details: undefined,
May  3 10:19:29 cs-be-s060 rocketchat[521039]:  errorType: 'Meteor.Error'
May  3 10:19:29 cs-be-s060 rocketchat[521039]: }
May  3 10:19:29 cs-be-s060 rocketchat[521039]: undefined undefined
```

**Comment by hanserasmus** [comment]
Also have this issue, users to both Nextcloud and Rocket.Chat is provided by the same LDAP server. Any further news on this issue?
